const textJson = {
    "canHead": "This simulation tests Bell's Inequalities using particles with '<i>real local properties</i>' before measurement.<br>The experiment is based on Schneider's paper <b>'Bell's Theorem and Negative Probabilities [I]'</b><br><i>(variables correspond with setup in [I], except that detectors B and C are swapped)</i>",
    "canFoot": "We model repeated creation of 3 correlated (<i>entangled</i>) photons (<i>a, b and c</i>). Each set of photons is created with the same polarization angle (<i>polarization angle between 0 and 360 degrees as measured on the same plane as the detectors</i>), randomly set when the photon's are created (<i>Einstein's realistic model</i>). We then measure the photons polarity as being within 180 degrees (<i>match=</i><b>+</b>) or not (<b>-</b>) of each of 3 detectors which are set to 0, 45 and 67.5 degrees.",
    "header1": "Realist Model View",
    "footer1": "Simple geometry tells us that if photon polarization is within 180 degrees of detectors set at 0 and 67.5 degrees, then they must also be within 180 degrees of the <i>in-between</i> detector set at 45 degrees (<i>cases 2 and 7</i>). However Bell's theorem (<i>according to Schneider [I]</i>) expects '<i>literally negative</i>' probabilities for cases 2 and 7 for the QM Model (<i>spooky action at a distance</i>), or greater than or equal to zero results for the Realist Model (<i>Eintein's local hidden variables</i>).",
    "header2": "QM Model View",
    "footer2": "When run long enough <i>(use [rate] or [+] button to speed up experiment)</i>, if QM expectations are met, (X+Y-Z)/2 < zero, then a Bell's experiment with <b>real local values before measurement</b> would have made the same predictions as expected for particles without real local values before measurement. However we see that the result is always zero, as that is the only result the simple-math used allows. Since we know that real-world tests produce negative values for (X+Y-Z)/2, apparently calculating negative values for cases 2 and 7. Not possible with the simple-math used in this experiment.<br><br><b>Questions:</b><br>What math is being used to calculate negative values for cases [2] and [7] and from what experimental results?<br>Would a simulated 'pilot wave' of some sort generate similar experimental results?<br>To be continued with a 'next version' of this experiment after further research... :)",
    "simLinks": "See forum discussion at <a href='http://www.sciphysicsforums.com/spfbb1/viewtopic.php?f=6&t=416' target='new'>http://www.sciphysicsforums.com/spfbb1/viewtopic.php?f=6&t=416</a>",
    "codeUrl": "https://github.com/tankersleyj/nobell",
    "appUrl": "https://codeserver.net/nb",
    "paperUrl": "https://sites.google.com/site/physicschecker/unsettled-physics/testing-bells-theorem-paper",
    "schneiderUrl1": "https://drchinese.com/David/Bell_Theorem_Easy_Math.htm",
    "schneiderUrl2": "http://drchinese.com/David/Bell_Theorem_Negative_Probabilities.htm"
}